### ISSUE TITLE
Is it possible to delegate/undelegate ONE directly in solidity smart contracts?

### ISSUE THREAD

**Issue by prayingmantissa** [harmony-one/sdk#105]
I see the Harmony SDK has features to delegate/undelegate by sending sgined transactions to an RPC using Typescript.

Is it possible to do the same thing in a solidity smart contract with a signed transaction from MetaMask or other wallets?

**Comment by rlan35** [comment]
It will be possible when this feature is launched. https://github.com/harmony-one/bounties/issues/77 It's currently under implementation.
