### ISSUE TITLE
HMY edit-validator ask for Absolute Path

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/sdk#12]
Trying to edit my validator on devnet by running the command bellow:

`./hmy staking edit-validator --validator-addr one1echapu535qgtc5ktkgjj3raec4x4gp0a2mh9ec --name Yelllowsin --identity Yelllowsin --website yelllowsin@harmony.one --security-contact Yellowsin --details "Maha Lakshmi" --rate 0.3 --min-self-delegation 2 --max-total-delegation 11000 --remove-bls-key 0xa8a0637c7e11e2ea82c23ec1c0dcae3963a34bbabd92b03f9d895d04377ac72ae770da75c4c5868490378501cbd3888e --add-bls-key 0xa8a0637c7e11e2ea82c23ec1c0dcae3963a34bbabd92b03f9d895d04377ac72ae770da75c4c5868490378501cbd3888e --chain-id devnet`

HMY returns with this error:

```
For bls public key: 0xa8a0637c7e11e2ea82c23ec1c0dcae3963a34bbabd92b03f9d895d04377ac72ae770da75c4c5868490378501cbd3888e
Enter the absolute path to the encrypted bls private key file:

Error: keypath is not absolute path
v179f4cf946: keypath is not absolute path
```

I am sure i am passing the correct BLS KEY parameter as this same parameter works for "create-validator" as shown bellow:

`./hmy staking create-validator --validator-addr one1echapu535qgtc5ktkgjj3raec4x4gp0a2mh9ec --name Yelllowsin --identity yelllowsin --website yelllowsin@harmony.one --security-contact Yelllowsin --details "Maha Lakshmi" --rate 0.3 --max-rate 0.9 --max-change-rate 0.05 --min-self-delegation 2 --max-total-delegation 11000 --amount 1000 --bls-pubkeys 0xa8a0637c7e11e2ea82c23ec1c0dcae3963a34bbabd92b03f9d895d04377ac72ae770da75c4c5868490378501cbd3888e --chain-id devnet`

**Comment by yelllowsin** [comment]
Issue created in the wrong place. Reopening on the correct one.

**Comment by rlan35** [comment]
We should streamline the bls key format and not include the 0x for all places.
