### ISSUE TITLE
Transactions to smart contracts fail silently

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/sdk#29]
While developing a dapp, I sent a transaction to a smart contract with insufficient gas. However, I got no indication that the transaction failed.

Now that the `hmy_sendRawTransaction` RPC returns an error if the transaction is unable to be submitted to the mem-pool, such errors should be 'reportable'.

Quickly inspecting the SDK, I found the following snippet:
https://github.com/harmony-one/sdk/blob/f90792fd917abe1c6cab8d5ad90df1ff41a4004b/packages/harmony-contract/src/methods/method.ts#L253-L261

Note that we never check if the transaction is rejected, maybe there is a good place to start.

**Comment by gupadhyaya** [comment]
@Daniel-VDM if you use `send` or `call` instead of `sendTransaction` it will get the receipt. `sendTransaction` api is made like this I guess. Also, you can see that, contract status is set to SENT and you are expected to call `confirm` following the call to `sendTransaction`. You can avoid these by directly using `send`.

**Comment by Daniel-VDM** [comment]
@gupadhyaya Yes I followed such structure, here is a snippet:

```javascript
contract.methods.startProject(
    testTitle,
    testDescription,
    testDuration,
    testAmount
).send({
    from: fromAccount,
}).then((res) => {
    const projectInfo = res.events.ProjectStarted.returnValues;
    console.log(projectInfo)
})
```

Correct me if I'm wrong, but I noticed that the returned value of `hmy_sendRawTransaction` is expected to be the transaction `id` (or hash). 
Here is the snippet:
https://github.com/harmony-one/sdk/blob/f90792fd917abe1c6cab8d5ad90df1ff41a4004b/packages/harmony-contract/src/methods/method.ts#L46-L57

The `id` is now `transaction failed:transaction underpriced` as that is what the RPC returns. So the confirm just hangs forever -- hence the silent failure.

**Comment by gupadhyaya** [comment]
for `send(options)` try manual gas like,
```
const options = {
  gasPrice: process.env.GAS_PRICE,
  gasLimit: process.env.GAS_LIMIT,
};
```

**Comment by Daniel-VDM** [comment]
> for `send(options)` try manual gas like,
> 
> ```
> const options = {
>   gasPrice: process.env.GAS_PRICE,
>   gasLimit: process.env.GAS_LIMIT,
> };
> ```

Setting the correct gas resolved the issue, but we should check and error if the transaction errored in my opinion.

**Comment by neeboo** [comment]
> @gupadhyaya Yes I followed such structure, here is a snippet:
> 
> ```js
> contract.methods.startProject(
>     testTitle,
>     testDescription,
>     testDuration,
>     testAmount
> ).send({
>     from: fromAccount,
> }).then((res) => {
>     const projectInfo = res.events.ProjectStarted.returnValues;
>     console.log(projectInfo)
> })
> ```
> 
> Correct me if I'm wrong, but I noticed that the returned value of `hmy_sendRawTransaction` is expected to be the transaction `id` (or hash).
> Here is the snippet:
> https://github.com/harmony-one/sdk/blob/f90792fd917abe1c6cab8d5ad90df1ff41a4004b/packages/harmony-contract/src/methods/method.ts#L46-L57
> 
> The `id` is now `transaction failed:transaction underpriced` as that is what the RPC returns. So the confirm just hangs forever -- hence the silent failure.

Thanks for pointing out, we should add error throwing before txn finished.

**Comment by peekpi** [comment]
#45 had fixed it.
https://github.com/harmony-one/sdk/blob/c49abc56916e6edf7aa959e38397ff280e47ec30/packages/harmony-contract/src/methods/method.ts#L54-L55
