### ISSUE TITLE
Math Wallet Deliverables and SDK Dependencies

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/sdk#3]
**Additional  Math Wallet Features**
- [ ] 1. When using a mnemonic pass phrase to create a wallet  would like to be able to generate multiple accounts
- [x] 2. When doing a transfer would like to get the transaction hash returned (moving forward this may be a link to explorer)
- [ ] 3. Would like to see transaction history for an account
- [x] 4. Would be nice if the balance of the account updated automatically after the transfer (currently requires a refresh)

**Comment by neeboo** [comment]
point 1: math wallet would not support this feature for all blockchain that integrated.
point 3: unless math wallet willing to runs a full-node, which does have some cost.

**Comment by neeboo** [comment]
Since Math-Wallet has no plan to add features like point 1 and point 3. We should close here
