### ISSUE TITLE
help: generating a bundle using browserify 

### ISSUE THREAD

**Issue by thelostone-mc** [harmony-one/sdk#56]
#### Description

I'm trying to generate a bundle of the harmony sdk so that I can use in a django app.
I've tried generating one for `@harmony-js/core` and it fails as it is unable to find scrypt-shim which comes from 
`@harmony-js/core`.
Could I some help in figuring how I'd go about including this package so that i can generate a js bundle that i can use in my app ? 

```
Error: Can't walk dependency graph: Cannot find module 'scrypt-shim' 
from '/Users/adianand/Labs/harmony-bundle/node_modules/@harmony-js/crypto/dist/keystore.js'
required by /Users/adianand/Labs/harmony-bundle/node_modules/@harmony-js/crypto/dist/keystore.js
``` 
https://github.com/thelostone-mc/harmony-bundle/issues/1

**Comment by thelostone-mc** [comment]
Doing a `npm i scrypt-shim` doesn't install 

I've tried `npm i github:web3-js/scrypt-shim` but since that package has a diff name aka web3-js/scrypt-shim, it doesn't work either

**Comment by neeboo** [comment]
> thelostone-mc/harmony-bundle#1

https://github.com/harmony-one/sdk#bundle

see this section, run ```yarn dist``` will generate bundle in `dist` folder

**Comment by thelostone-mc** [comment]
Thanks for this
